var myName1="Harni";
console.log(myName1);
var myAge1=21;
console.log(myAge1);
var myCity1;
myCity1="Madurai";
console.log(myCity1);
var number1=20;
number1=40;
console.log(number1);
var color="Red";
var color="Blue";
console.log(color);
var name2="Harni";
var age2=21;
var city2="Madurai";
console.log(name2);
console.log(age2);
console.log(city2);
var collegeName="SRM TRP COLLEGE";
console.log(collegeName);
var favoriteSubject="JavaScript";
console.log(favoriteSubject);
var number=10;
number=20;
number=30;
number=40;
console.log(number);
var salary=20000;
salary=25000;
console.log(salary);
let studentName="Harni";
console.log(studentName);
let studentAge=21;
console.log(studentAge);
let qualification;
qualification="B.E CSE";
console.log(qualification);
let amount=100;
amount=200;
console.log(amount);
let name3="Harni";
let qualification3="B.E CSE";
let location3="Madurai";
console.log(name3);
console.log(qualification3);
console.log(location3);
let course="JavaScript";
console.log(course);
let marks=50;
marks=80;
console.log(marks);
let companyName="Stackly";
console.log(companyName);
let experience=0;
console.log(experience);
let mobileModel="realme 12 pro plus";
console.log(mobileModel);
const  myFullName="Harni";
console.log(myFullName);
const dateOfBirth="22-02-2005";
console.log(dateOfBirth);
const company="Stackly";
console.log(company);
const country="India";
console.log(country);
const personName="Harni";
const personAge=21;
const personCity="Madurai";
console.log(personName);
console.log(personAge);
console.log(personCity);
const courseName="JavaScript";
console.log(courseName);
const favoriteColor="purple";
console.log(favoriteColor);
const employeeId="STK-6115";
console.log(employeeId);
const officeLocation="Salem";
console.log(officeLocation);
console.log(100);
console.log("Harni");
console.log(21);
console.log("B.E.CSE");
console.log("Welcome to JavaScript");
console.log("Harni");
console.log(21);
console.log("Madurai");
console.log("B.E.CSE");
console.log(true);
var userName="Harni";
console.log(userName);
var userAge=21;
console.log(userAge);
console.log("Harni",21,"Madurai","B.E CSE");
alert ("Welcome to JavaScript");
var alertName ="Harni";
alert(alertName);
var askName=prompt("What is your name?");
alert(askName);
var askAge=prompt("What is your age?");
alert(askAge);
var askQualification=prompt("What is your qualification?");
alert(askQualification);
var askCity=prompt("What is your city?");
console.log(askCity);
confirm("Do you know JavaScript?");
confirm("Do you want to continue?");
var name47=prompt("Enter yoyr name");
var qualification47=prompt("Enter your qualification");
document.writeln(name47+"<br>");
document.writeln(qualification47+"<br>");
var greeting="Hello Everyone";
document.writeln(greeting+"<br>");
console.log("Harni");
console.warn("B.E CSE");
console.error("Madurai");
console.log("Completed all 50 tasks");
document.writeln("completed");